### ISSUE TITLE
TSP tutorial won't work as expected

### ISSUE THREAD

**Issue by igarashi339** [mdrft/Wildqat#86]
In [TSP tutorial](https://github.com/mdrft/Wildqat/blob/master/examples_ja/tutorial015_travelling_salesman.ipynb), execute result is not a optimal Hamilton cycle in my local execution.
It is because the QUBO matrix doesn't contain distance cost information.
So, I think that `\` should be inserted at setting `a.qubo`.

**Comment by Morning777** [comment]
Thank you for pointing this out. I have fixed the code.
